export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const SAVE_MARVEL_CHARACTERS = 'SAVE_MARVEL_CHARACTERS'
export const SET_LOADING_FLAG = 'SET_LOADING_FLAG'
export const SET_CLIENT_RECT = 'SET_CLIENT_RECT'
